"""
rag_ingest.py
=============
Ingests sample documents into Chroma via LlamaIndex. Embeddings are
generated by calling OUR Model Gateway's /embed endpoint - keeping this
consistent with every other LLM-related call in the system, which all go
through the gateway rather than hitting a provider directly. This also
means embedding calls are visible in the gateway's cost tracking, same as
every chat/planner/evaluator call.
"""

import os
import requests
import chromadb
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex, StorageContext
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core.embeddings import BaseEmbedding

MODEL_GATEWAY_URL = os.environ.get("MODEL_GATEWAY_URL", "http://model-gateway:8080")


class GatewayEmbedding(BaseEmbedding):
    """
    A custom LlamaIndex embedding class that doesn't call OpenAI directly -
    instead, every embedding request goes through our own Model Gateway's
    /embed endpoint, keeping this consistent with every other LLM call
    in the system (planner, analyst, evaluator, etc. all go through the
    gateway too).
    """

    def _get_text_embedding(self, text: str) -> list[float]:
        response = requests.post(
            f"{MODEL_GATEWAY_URL}/embed",
            json={"text": text},
            timeout=30,
        )
        response.raise_for_status()
        return response.json()["embedding"]

    def _get_query_embedding(self, query: str) -> list[float]:
        # Queries and documents use the identical embedding call here -
        # some embedding models support separate query-vs-document modes,
        # but text-embedding-3-small does not, so this stays the same.
        return self._get_text_embedding(query)

    async def _aget_query_embedding(self, query: str) -> list[float]:
        return self._get_query_embedding(query)


# --- Step A: connect to the Chroma container that's already running ---
# This is the SAME Chroma instance from docker-compose.yml - we're not
# spinning up a new vector store, just connecting to the existing one.
chroma_client = chromadb.HttpClient(host="chroma", port=8000)

# A "collection" in Chroma is like a table - a named group of vectors.
# Using a distinct collection name ("documents") keeps this separate from
# any future conversation-memory collection, which will get its own name.
chroma_collection = chroma_client.get_or_create_collection("documents")

# --- Step B: wrap that Chroma collection so LlamaIndex knows how to use it ---
# ChromaVectorStore is LlamaIndex's adapter - it translates LlamaIndex's
# internal calls ("store this embedding", "search for similar vectors")
# into the specific API calls Chroma actually expects.
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

# StorageContext bundles together WHERE things get stored - here, just
# our vector store, but this same object could also coordinate a separate
# document-store or index-store if we needed one.
storage_context = StorageContext.from_defaults(vector_store=vector_store)

embed_model = GatewayEmbedding()


def run_ingestion():
    documents = SimpleDirectoryReader("sample_docs").load_data()
    print(f"Loaded {len(documents)} document(s) from sample_docs/")

    index = VectorStoreIndex.from_documents(
        documents,
        storage_context=storage_context,
        embed_model=embed_model,
    )

    print("Ingestion complete. Chunks are now embedded and stored in Chroma.")
    return index


if __name__ == "__main__":
    run_ingestion()